"""loan terms + installment paid_amount

Revision ID: 2d154b9bc36c
Revises: 13bc02258d84
Create Date: 2026-06-03 02:44:31.763675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d154b9bc36c'
down_revision: Union[str, Sequence[str], None] = '13bc02258d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installments', sa.Column('due_amount', sa.Integer(), nullable=False))
    op.add_column('installments', sa.Column('paid_amount', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('installments_loan_id_fkey'), 'installments', type_='foreignkey')
    op.drop_constraint(op.f('installments_payment_id_fkey'), 'installments', type_='foreignkey')
    op.create_foreign_key(None, 'installments', 'loans', ['loan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('installments', 'amount')
    op.drop_column('installments', 'payment_id')
    op.add_column('loans', sa.Column('interest_type', sa.String(length=10), nullable=False))
    op.add_column('loans', sa.Column('interest_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('loans', sa.Column('disbursed', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('repayable', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('profit', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('frequency_meta', sa.JSON(), nullable=True))
    op.add_column('loans', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('loans', sa.Column('close_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_loans_collector_id'), 'loans', ['collector_id'], unique=False)
    op.create_index(op.f('ix_loans_customer_id'), 'loans', ['customer_id'], unique=False)
    op.drop_column('loans', 'interest_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_loans_customer_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_collector_id'), table_name='loans')
    op.drop_column('loans', 'close_reason')
    op.drop_column('loans', 'closed_at')
    op.drop_column('loans', 'frequency_meta')
    op.drop_column('loans', 'profit')
    op.drop_column('loans', 'repayable')
    op.drop_column('loans', 'disbursed')
    op.drop_column('loans', 'interest_value')
    op.drop_column('loans', 'interest_type')
    op.add_column('installments', sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('installments', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'installments', type_='foreignkey')
    op.create_foreign_key(op.f('installments_payment_id_fkey'), 'installments', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(op.f('installments_loan_id_fkey'), 'installments', 'loans', ['loan_id'], ['id'])
    op.drop_column('installments', 'paid_amount')
    op.drop_column('installments', 'due_amount')
    # ### end Alembic commands ###
